// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI_Labb1.Data;

#nullable disable

namespace MinimalAPI_Labb1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240905104232_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI_Labb1.Models.Books", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter",
                            Description = "In the novels, Harry is described as having his father's perpetually untidy black hair, his mother's bright green eyes, and a lightning bolt-shaped scar on his forehead. He is short and skinny for his age, with a thin face and \"knobbly\" knees, and he wears Windsor glasses.",
                            Genre = "Fantasy",
                            IsAvailable = true
                        },
                        new
                        {
                            ID = 2,
                            Author = "Tolken",
                            BookTitle = "Lord of the rings",
                            Description = "The plot of The Lord of the Rings is about the war of the peoples of the fantasy world Middle-earth against a dark lord known as \"Sauron.\" At the same time they try to destroy a ring which would give Sauron a lot of power if he got it, but the only place to destroy the ring is deep into Sauron's land Mordor.",
                            Genre = "Fantasy",
                            IsAvailable = false
                        },
                        new
                        {
                            ID = 3,
                            Author = "Robert Heinlein",
                            BookTitle = "StarShip Troopers",
                            Description = "In the distant future, the Earth is at war with a race of giant alien insects. Little is known about the Bugs except that they are intent on the eradication of all human life. But there was a time before the war... A Mobile Infantry travels to distant alien planets to take the war to the Bugs. They are a ruthless enemy with only one mission: Survival of their species no matter what the cost...",
                            Genre = "Sci-fi",
                            IsAvailable = false
                        },
                        new
                        {
                            ID = 4,
                            Author = "Stephen King",
                            BookTitle = "The Shining",
                            Description = " A family heads to an isolated hotel for the winter, where a sinister presence influences the father into violence. At the same time, his psychic son sees horrifying forebodings from both the past and the future.",
                            Genre = "Horror",
                            IsAvailable = true
                        },
                        new
                        {
                            ID = 5,
                            Author = "Lucy Foley",
                            BookTitle = "The Guest List",
                            Description = "The story takes place at the wedding of Jules Keegan and Will Slater, which is being held on an island off the coast of Ireland. The plot has been compared to the works of Agatha Christie, as a murder occurs with limited suspects and each guest has a secret which will be revealed.",
                            Genre = "Thriller",
                            IsAvailable = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
